name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
           echo "--before"
           docker ps
           docker network create todo-app 
           docker run -dp 127.0.0.1:3000:3000 -w /app -v "$(pwd):/app" --network todo-app -e MYSQL_HOST=mysql -e MYSQL_USER=root -e MYSQL_PASSWORD=secret  -e MYSQL_DB=todos    node:18-alpine    sh -c "yarn install && yarn run dev"
           echo "after docker cmd "
           docker ps
           
